# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/wordle_design/wordle_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design || ORIG_REF_NAME==wordle_design} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_zynq_ultra_ps_e_0_0/wordle_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==wordle_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_wordle_top_0_0/wordle_design_wordle_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_wordle_top_0_0 || ORIG_REF_NAME==wordle_design_wordle_top_0_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_0_0/wordle_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_0_0 || ORIG_REF_NAME==wordle_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_1_0/wordle_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_1_0 || ORIG_REF_NAME==wordle_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_2_0/wordle_design_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_2_0 || ORIG_REF_NAME==wordle_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_3_0/wordle_design_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_3_0 || ORIG_REF_NAME==wordle_design_axi_gpio_3_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_4_0/wordle_design_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_4_0 || ORIG_REF_NAME==wordle_design_axi_gpio_4_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_5_0/wordle_design_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_5_0 || ORIG_REF_NAME==wordle_design_axi_gpio_5_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_gpio_6_0/wordle_design_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_gpio_6_0 || ORIG_REF_NAME==wordle_design_axi_gpio_6_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_axi_smc_0/wordle_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_axi_smc_0 || ORIG_REF_NAME==wordle_design_axi_smc_0} -quiet] -quiet

# IP: bd/wordle_design/ip/wordle_design_rst_ps8_0_99M_0/wordle_design_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wordle_design_rst_ps8_0_99M_0 || ORIG_REF_NAME==wordle_design_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/wordle_design_ooc.xdc
