# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/g55wang/lab1_system/lab1_system.srcs/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1.xci
# IP: The module: 'alu_design_axi_gpio_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/g55wang/lab1_system/lab1_system.srcs/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1.xci
# IP: The module: 'alu_design_axi_gpio_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
