# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/g55wang/lab2_system/lab2_system.srcs/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/wordle_design_axi_smc_0.xci
# IP: The module: 'wordle_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/bd_221d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_0/bd_221d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_1/bd_221d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_2/bd_221d_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_3/bd_221d_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_4/bd_221d_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_5/bd_221d_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_6/bd_221d_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_7/bd_221d_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_8/bd_221d_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_9/bd_221d_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_10/bd_221d_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_11/bd_221d_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_12/bd_221d_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_13/bd_221d_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_14/bd_221d_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_15/bd_221d_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_16/bd_221d_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_17/bd_221d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_18/bd_221d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_19/bd_221d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_20/bd_221d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_21/bd_221d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_22/bd_221d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_23/bd_221d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_24/bd_221d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_25/bd_221d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_26/bd_221d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_27/bd_221d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_28/bd_221d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_29/bd_221d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_30/bd_221d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_31/bd_221d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_32/bd_221d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_33/bd_221d_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_34/bd_221d_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_35/bd_221d_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_36/bd_221d_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_37/bd_221d_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_38/bd_221d_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_39/bd_221d_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_40/bd_221d_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_41/bd_221d_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_42/bd_221d_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_43/bd_221d_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_44/bd_221d_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_45/bd_221d_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_46/bd_221d_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_47/bd_221d_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_48/bd_221d_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_49/bd_221d_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_50/bd_221d_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_51/bd_221d_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_52/bd_221d_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_53/bd_221d_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_54/bd_221d_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_55/bd_221d_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_56/bd_221d_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_57/bd_221d_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_58/bd_221d_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_59/bd_221d_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_60/bd_221d_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_61/bd_221d_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_62/bd_221d_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_63/bd_221d_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_64/bd_221d_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_65/bd_221d_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_66/bd_221d_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_67/bd_221d_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_68/bd_221d_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_69/bd_221d_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_70/bd_221d_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_71/bd_221d_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_72/bd_221d_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_73/bd_221d_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_74/bd_221d_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_1/bd_221d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_1/bd_221d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_2/bd_221d_arinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_3/bd_221d_rinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_4/bd_221d_awinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_5/bd_221d_winsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_6/bd_221d_binsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_7/bd_221d_aroutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_8/bd_221d_routsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_9/bd_221d_awoutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_10/bd_221d_woutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_11/bd_221d_boutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_12/bd_221d_arni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_13/bd_221d_rni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_14/bd_221d_awni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_15/bd_221d_wni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_16/bd_221d_bni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_20/bd_221d_s00a2s_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_21/bd_221d_sarn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_22/bd_221d_srn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_23/bd_221d_sawn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_24/bd_221d_swn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_25/bd_221d_sbn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_26/bd_221d_m00s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_27/bd_221d_m00arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_28/bd_221d_m00rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_29/bd_221d_m00awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_30/bd_221d_m00wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_31/bd_221d_m00bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_33/bd_221d_m01s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_34/bd_221d_m01arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_35/bd_221d_m01rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_36/bd_221d_m01awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_37/bd_221d_m01wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_38/bd_221d_m01bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_40/bd_221d_m02s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_41/bd_221d_m02arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_42/bd_221d_m02rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_43/bd_221d_m02awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_44/bd_221d_m02wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_45/bd_221d_m02bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_47/bd_221d_m03s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_48/bd_221d_m03arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_49/bd_221d_m03rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_50/bd_221d_m03awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_51/bd_221d_m03wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_52/bd_221d_m03bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_54/bd_221d_m04s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_55/bd_221d_m04arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_56/bd_221d_m04rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_57/bd_221d_m04awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_58/bd_221d_m04wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_59/bd_221d_m04bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_61/bd_221d_m05s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_62/bd_221d_m05arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_63/bd_221d_m05rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_64/bd_221d_m05awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_65/bd_221d_m05wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_66/bd_221d_m05bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_68/bd_221d_m06s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_69/bd_221d_m06arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_70/bd_221d_m06rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_71/bd_221d_m06awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_72/bd_221d_m06wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_73/bd_221d_m06bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/g55wang/lab2_system/lab2_system.srcs/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/wordle_design_axi_smc_0.xci
# IP: The module: 'wordle_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/bd_221d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_0/bd_221d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_1/bd_221d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_2/bd_221d_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_3/bd_221d_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_4/bd_221d_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_5/bd_221d_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_6/bd_221d_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_7/bd_221d_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_8/bd_221d_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_9/bd_221d_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_10/bd_221d_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_11/bd_221d_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_12/bd_221d_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_13/bd_221d_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_14/bd_221d_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_15/bd_221d_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_16/bd_221d_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_17/bd_221d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_18/bd_221d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_19/bd_221d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_20/bd_221d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_21/bd_221d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_22/bd_221d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_23/bd_221d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_24/bd_221d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_25/bd_221d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_26/bd_221d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_27/bd_221d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_28/bd_221d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_29/bd_221d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_30/bd_221d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_31/bd_221d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_32/bd_221d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_33/bd_221d_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_34/bd_221d_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_35/bd_221d_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_36/bd_221d_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_37/bd_221d_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_38/bd_221d_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_39/bd_221d_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_40/bd_221d_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_41/bd_221d_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_42/bd_221d_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_43/bd_221d_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_44/bd_221d_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_45/bd_221d_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_46/bd_221d_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_47/bd_221d_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_48/bd_221d_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_49/bd_221d_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_50/bd_221d_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_51/bd_221d_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_52/bd_221d_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_53/bd_221d_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_54/bd_221d_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_55/bd_221d_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_56/bd_221d_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_57/bd_221d_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_58/bd_221d_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_59/bd_221d_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_60/bd_221d_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_61/bd_221d_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_62/bd_221d_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_63/bd_221d_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_64/bd_221d_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_65/bd_221d_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_66/bd_221d_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_67/bd_221d_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_68/bd_221d_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_69/bd_221d_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_70/bd_221d_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_71/bd_221d_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_72/bd_221d_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_73/bd_221d_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_74/bd_221d_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_1/bd_221d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_1/bd_221d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_2/bd_221d_arinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_3/bd_221d_rinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_4/bd_221d_awinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_5/bd_221d_winsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_6/bd_221d_binsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_7/bd_221d_aroutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_8/bd_221d_routsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_9/bd_221d_awoutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_10/bd_221d_woutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_11/bd_221d_boutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_12/bd_221d_arni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_13/bd_221d_rni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_14/bd_221d_awni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_15/bd_221d_wni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_16/bd_221d_bni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_20/bd_221d_s00a2s_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_21/bd_221d_sarn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_22/bd_221d_srn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_23/bd_221d_sawn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_24/bd_221d_swn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_25/bd_221d_sbn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_26/bd_221d_m00s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_27/bd_221d_m00arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_28/bd_221d_m00rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_29/bd_221d_m00awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_30/bd_221d_m00wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_31/bd_221d_m00bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_33/bd_221d_m01s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_34/bd_221d_m01arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_35/bd_221d_m01rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_36/bd_221d_m01awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_37/bd_221d_m01wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_38/bd_221d_m01bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_40/bd_221d_m02s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_41/bd_221d_m02arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_42/bd_221d_m02rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_43/bd_221d_m02awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_44/bd_221d_m02wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_45/bd_221d_m02bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_47/bd_221d_m03s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_48/bd_221d_m03arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_49/bd_221d_m03rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_50/bd_221d_m03awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_51/bd_221d_m03wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_52/bd_221d_m03bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_54/bd_221d_m04s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_55/bd_221d_m04arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_56/bd_221d_m04rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_57/bd_221d_m04awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_58/bd_221d_m04wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_59/bd_221d_m04bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_61/bd_221d_m05s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_62/bd_221d_m05arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_63/bd_221d_m05rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_64/bd_221d_m05awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_65/bd_221d_m05wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_66/bd_221d_m05bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_68/bd_221d_m06s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_69/bd_221d_m06arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_70/bd_221d_m06rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_71/bd_221d_m06awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_72/bd_221d_m06wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/bd_0/ip/ip_73/bd_221d_m06bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
