# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/alu_design/alu_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design || ORIG_REF_NAME==alu_design} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_zynq_ultra_ps_e_0_1/alu_design_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==alu_design_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_axi_gpio_0_1/alu_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_axi_gpio_0_1 || ORIG_REF_NAME==alu_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_axi_gpio_1_1/alu_design_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_axi_gpio_1_1 || ORIG_REF_NAME==alu_design_axi_gpio_1_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_axi_gpio_2_1/alu_design_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_axi_gpio_2_1 || ORIG_REF_NAME==alu_design_axi_gpio_2_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_axi_gpio_3_1/alu_design_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_axi_gpio_3_1 || ORIG_REF_NAME==alu_design_axi_gpio_3_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_alu_0_1/alu_design_alu_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_alu_0_1 || ORIG_REF_NAME==alu_design_alu_0_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_rst_ps8_0_99M_1/alu_design_rst_ps8_0_99M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_rst_ps8_0_99M_1 || ORIG_REF_NAME==alu_design_rst_ps8_0_99M_1} -quiet] -quiet

# IP: bd/alu_design/ip/alu_design_axi_smc_1/alu_design_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==alu_design_axi_smc_1 || ORIG_REF_NAME==alu_design_axi_smc_1} -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/alu_design_ooc.xdc
