domain_path: C:\Users\g55wang\lab2_system\lab2_system.sw\wordle_design_wrapper\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: C:\Software\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
