# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/g55wang/lab2_system/lab2_system.srcs/sources_1/bd/wordle_design/ip/wordle_design_wordle_top_0_0/wordle_design_wordle_top_0_0.xci
# IP: The module: 'wordle_design_wordle_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_wordle_top_0_0/src/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_design_wordle_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/g55wang/lab2_system/lab2_system.srcs/sources_1/bd/wordle_design/ip/wordle_design_wordle_top_0_0/wordle_design_wordle_top_0_0.xci
# IP: The module: 'wordle_design_wordle_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/g55wang/lab2_system/lab2_system.gen/sources_1/bd/wordle_design/ip/wordle_design_wordle_top_0_0/src/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'wordle_design_wordle_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
