# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/g55wang/lab1_system/lab1_system.srcs/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/alu_design_axi_smc_1.xci
# IP: The module: 'alu_design_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/bd_f990.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_0/bd_f990_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_1/bd_f990_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_2/bd_f990_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_3/bd_f990_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_4/bd_f990_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_5/bd_f990_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_6/bd_f990_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_7/bd_f990_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_8/bd_f990_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_9/bd_f990_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_10/bd_f990_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_11/bd_f990_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_12/bd_f990_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_13/bd_f990_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_14/bd_f990_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_15/bd_f990_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_16/bd_f990_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_17/bd_f990_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_18/bd_f990_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_19/bd_f990_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_20/bd_f990_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_21/bd_f990_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_22/bd_f990_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_23/bd_f990_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_24/bd_f990_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_25/bd_f990_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_26/bd_f990_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_27/bd_f990_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_28/bd_f990_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_29/bd_f990_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_30/bd_f990_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_31/bd_f990_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_32/bd_f990_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_33/bd_f990_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_34/bd_f990_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_35/bd_f990_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_36/bd_f990_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_37/bd_f990_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_38/bd_f990_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_39/bd_f990_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_40/bd_f990_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_41/bd_f990_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_42/bd_f990_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_43/bd_f990_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_44/bd_f990_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_45/bd_f990_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_46/bd_f990_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_47/bd_f990_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_48/bd_f990_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_49/bd_f990_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_50/bd_f990_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_51/bd_f990_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_52/bd_f990_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_53/bd_f990_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_1/bd_f990_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_1/bd_f990_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_2/bd_f990_arinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_3/bd_f990_rinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_4/bd_f990_awinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_5/bd_f990_winsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_6/bd_f990_binsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_7/bd_f990_aroutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_8/bd_f990_routsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_9/bd_f990_awoutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_10/bd_f990_woutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_11/bd_f990_boutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_12/bd_f990_arni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_13/bd_f990_rni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_14/bd_f990_awni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_15/bd_f990_wni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_16/bd_f990_bni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_20/bd_f990_s00a2s_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_21/bd_f990_sarn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_22/bd_f990_srn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_23/bd_f990_sawn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_24/bd_f990_swn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_25/bd_f990_sbn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_26/bd_f990_m00s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_27/bd_f990_m00arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_28/bd_f990_m00rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_29/bd_f990_m00awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_30/bd_f990_m00wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_31/bd_f990_m00bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_33/bd_f990_m01s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_34/bd_f990_m01arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_35/bd_f990_m01rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_36/bd_f990_m01awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_37/bd_f990_m01wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_38/bd_f990_m01bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_40/bd_f990_m02s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_41/bd_f990_m02arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_42/bd_f990_m02rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_43/bd_f990_m02awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_44/bd_f990_m02wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_45/bd_f990_m02bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_47/bd_f990_m03s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_48/bd_f990_m03arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_49/bd_f990_m03rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_50/bd_f990_m03awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_51/bd_f990_m03wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_52/bd_f990_m03bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/g55wang/lab1_system/lab1_system.srcs/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/alu_design_axi_smc_1.xci
# IP: The module: 'alu_design_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/bd_f990.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_0/bd_f990_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_1/bd_f990_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_2/bd_f990_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_3/bd_f990_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_4/bd_f990_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_5/bd_f990_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_6/bd_f990_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_7/bd_f990_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_8/bd_f990_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_9/bd_f990_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_10/bd_f990_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_11/bd_f990_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_12/bd_f990_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_13/bd_f990_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_14/bd_f990_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_15/bd_f990_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_16/bd_f990_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_17/bd_f990_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_18/bd_f990_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_19/bd_f990_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_20/bd_f990_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_21/bd_f990_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_22/bd_f990_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_23/bd_f990_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_24/bd_f990_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_25/bd_f990_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_26/bd_f990_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_27/bd_f990_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_28/bd_f990_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_29/bd_f990_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_30/bd_f990_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_31/bd_f990_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_32/bd_f990_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_33/bd_f990_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_34/bd_f990_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_35/bd_f990_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_36/bd_f990_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_37/bd_f990_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_38/bd_f990_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_39/bd_f990_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_40/bd_f990_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_41/bd_f990_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_42/bd_f990_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_43/bd_f990_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_44/bd_f990_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_45/bd_f990_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_46/bd_f990_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_47/bd_f990_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_48/bd_f990_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_49/bd_f990_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_50/bd_f990_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_51/bd_f990_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_52/bd_f990_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_53/bd_f990_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_1/bd_f990_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_1/bd_f990_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_2/bd_f990_arinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_3/bd_f990_rinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_4/bd_f990_awinsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_5/bd_f990_winsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_6/bd_f990_binsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_7/bd_f990_aroutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_8/bd_f990_routsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_9/bd_f990_awoutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_10/bd_f990_woutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_11/bd_f990_boutsw_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_12/bd_f990_arni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_13/bd_f990_rni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_14/bd_f990_awni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_15/bd_f990_wni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_16/bd_f990_bni_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_20/bd_f990_s00a2s_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_21/bd_f990_sarn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_22/bd_f990_srn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_23/bd_f990_sawn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_24/bd_f990_swn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_25/bd_f990_sbn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_26/bd_f990_m00s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_27/bd_f990_m00arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_28/bd_f990_m00rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_29/bd_f990_m00awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_30/bd_f990_m00wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_31/bd_f990_m00bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_33/bd_f990_m01s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_34/bd_f990_m01arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_35/bd_f990_m01rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_36/bd_f990_m01awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_37/bd_f990_m01wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_38/bd_f990_m01bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_40/bd_f990_m02s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_41/bd_f990_m02arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_42/bd_f990_m02rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_43/bd_f990_m02awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_44/bd_f990_m02wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_45/bd_f990_m02bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_47/bd_f990_m03s2a_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_48/bd_f990_m03arn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_49/bd_f990_m03rn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_50/bd_f990_m03awn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_51/bd_f990_m03wn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/bd_0/ip/ip_52/bd_f990_m03bn_0_ooc.xdc

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/g55wang/lab1_system/lab1_system.gen/sources_1/bd/alu_design/ip/alu_design_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'alu_design_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
